### ISSUE TITLE
Structure Ruby SDK for i3s

### ISSUE THREAD

**Issue by aalexmonteiro** [HewlettPackard/oneview-sdk-ruby#122]
### Scenario/Intent
You need to structure Ruby SDK for implementation of resources and unit tests for i3s.

### Environment Details
 - **OneView SDK Version: Future
 - **OneView Appliance Version: 300
 - **OneView Client API Version: 300
 - **Ruby Version: 2.2.3+
 - **Platform: w/e

### Expected Result
Ruby SDK is structured for implementation of i3s.

### Actual Result
Ruby SDK is not structured for implementation of i3s.

**Comment by jsmartt** [comment]
@aalexmonteiro , what do you suggest for a restructure?

**Comment by aalexmonteiro** [comment]
@jsmartt  I've already implemented something simple, similar to what exists for other resources. But good suggestions are welcome. I created the OneViewSDK :: API300 :: ImageStreamer module, classes and unit tests, without implementation. If you want to check, you can see the branch feature/i3s_structure. Soon I will open the PR.
