### ISSUE TITLE
Some integration tests are failing

### ISSUE THREAD

**Issue by ricardogpsf** [HewlettPackard/oneview-sdk-ruby#127]
### Scenario/Intent
Some integration tests are failing for api200 and api300 (both C7000 and Synergy) due dependencies of data throught the tests.

### Steps to Reproduce
Execute "spec:integration:api" for the api that you want test

### Expected Result
All tests with success (except the tests that are expected to fail, due missing a required file for test, bug on doc / api)

### Actual Result
- [x] ServerProfile (api200, api300/c7000)
- [x] UplinkSet (api200, api300/c7000)
- [x] VolumeAttachment (api200, api300/c7000)
- [x] Interconnect api200, api300/c7000)
- [ ] Enclosure (api300/synergy)
- [x] LogicalEnclosure (api200)

**Comment by tmiotto** [comment]
What tests? Where are the logs?

**Comment by ricardogpsf** [comment]
@tmiotto ,
The tests with dependencies problems for api300/c7k were fixed (in a local branch for now).

I am working in the tests with dependencies problems for api200/c7k, the log was attached, 7 tests are failing, but just 2 are unexpected fail (2 tests of ManagedSAN).
[log_api200.txt](https://github.com/HewlettPackard/oneview-sdk-ruby/files/697101/log_api200.txt)

Some tests with dependencies problems for api300/synergy are failing (but I didn't save the log, I will execute the tests again and get the log)
