### ISSUE TITLE
Logical Downlink method at API300 - self.get_without_ethernet - should accept an argument

### ISSUE THREAD

**Issue by fgbulsoni** [HewlettPackard/oneview-sdk-ruby#129]
### Scenario/Intent
Run the self.get_without_ethernet method from the resource logical downlink on API300, and receive method unavailable

### Environment Details
 - **OneView SDK Version:** 3.1.0
 - **OneView Appliance Version:** 3.0
 - **OneView Client API Version:** 300
 - **Ruby Version:** 2.2.3
 - **Platform:** Windows

### Steps to Reproduce
Run OneviewSDK::API300::C7000::LogicalDownlink.get_without_ethernet(client)

### Expected Result
Method unavailable, since the endpoint has been dropped

### Actual Result
wrong number of arguments (1 for 0)
Since the method on 300 is listed without an argument, while the one on 200 had the argument.

**Comment by tmiotto** [comment]
Closing it since it is part of #131
