### ISSUE TITLE
Why API300::Synergy::LogicalSwitchGroup ?

### ISSUE THREAD

**Issue by tmiotto** [HewlettPackard/oneview-sdk-ruby#134]
### Scenario/Intent
I'm trying to understand why the SDK has the **API300::Synergy::LogicalSwitchGroup** if it won't do anything. If the resource cease to exists probably we don't want it to be there instead creating and making all methods unavailable.

### Environment Details
 - **OneView SDK Version:** 3.1.0

### Steps to Reproduce
Open `lib/oneview-sdk/resource/api300/synergy/`

### Expected Result
Probably I won't need to have the `logical_switch_group.rb` file.

### Actual Result
I would see the `logical_switch_group.rb` file implementing the LogicalSwitchGroup without any method available.

**Comment by ricardogpsf** [comment]
This thinking works for logical_switch too.
The documentation has not logical_switch reference.

**Comment by jsmartt** [comment]
Good point. Shall I remove it from my open PR too?

**Comment by ricardogpsf** [comment]
No. I was wrong. LogicalSwitch have actions for another API.
