### ISSUE TITLE
CHANGELOG notes for v3.1.0 changed after the release

### ISSUE THREAD

**Issue by jsmartt** [HewlettPackard/oneview-sdk-ruby#138]
The section in the CHANGELOG for the v3.1.0 release was modified after the release, giving an unclear picture of the current state of the repo and what has been released. See the CHANGELOG at [v3.1.0](https://github.com/HewlettPackard/oneview-sdk-ruby/blob/v3.1.0/CHANGELOG.md) and [now](https://github.com/HewlettPackard/oneview-sdk-ruby/blob/master/CHANGELOG.md)

**Comment by tmiotto** [comment]
As I see in the history, this was caused by the commit [Updated CHANGELOG and required i3s module](https://github.com/HewlettPackard/oneview-sdk-ruby/commit/a799ef27fd839e2e8b55d7d0525c0436640a5e05) in the PR #123

**Comment by fgbulsoni** [comment]
Indeed, it seems some changes went into 3.1.0 and that should be avoided. These new changes are not contained in 3.1.0 and therefore they should not be listed in it. 
I'd propose that the changelog for 3.1.0 be changed back to what it was on release, and a new proposed version is added to the changelog with the changes.

**Comment by aalexmonteiro** [comment]
@tmiotto , exactly.

Could be like that? What do you think?

# Unreleased Changes
**Proposed Version:** v3.1.0

# v3.1.0

**Comment by tmiotto** [comment]
Maybe we could add:

**Proposed Version:** v3.2.0

to the CHANGELOG

**Comment by jsmartt** [comment]
@tmiotto , sorry, I saw your last comment after it was already merged. I guess someone can add the proposed version in one of the open/future PRs
