### ISSUE TITLE
REST methods should handle redirects

### ISSUE THREAD

**Issue by jsmartt** [HewlettPackard/oneview-sdk-ruby#145]
### Scenario/Intent
The REST methods should handle redirects. One issue I've already run into is that for Synergy Enclsoures, trying to get the script (`enc.script`) gives a 301 error message saying it has moved to a LogicalEnclosure uri.

I think we could implements something pretty similar to [this](http://stackoverflow.com/a/6934503/2456552), where we only follow redirects up to 3 or 5 times.

Because we need the data to re-submit the request, we'll need to handle this in the [rest_api](https://github.com/HewlettPackard/oneview-sdk-ruby/blob/master/lib/oneview-sdk/rest.rb#L31) method, not response_handler.

### Environment Details
 - **OneView SDK Version:** 3.1.0
 - **OneView Appliance Version:** All
 - **OneView Client API Version:** All

### Steps to Reproduce
With a client using api_version 300 as `@client`, talking to a v300 DCS...

```ruby
@client.api_version = 300
OneviewSDK.api_version = 300
OneviewSDK::API300.variant = 'Synergy'

e = @client.get_all(:Enclosures).first
e.script
```

### Expected Result
It to be able to get the script (following any redirects needed to get there)

### Actual Result
I get this error:

```ruby
OneviewSDK::RequestError: 301
from /usr/local/rvm/gems/ruby-2.2.4/gems/oneview-sdk-3.1.0/lib/oneview-sdk/rest.rb:162:in `response_handler'
```

**Comment by jsmartt** [comment]
@tmiotto , @ricardogpsf , @aalexmonteiro , @fgbulsoni or @piantola , do any of you have any concerns with this, or shall I implement it?

**Comment by tmiotto** [comment]
@jsmartt I have one concern that is to avoid being eternally redirected, maybe we should have a limit for it, or timeout.

By the way, I'm okay with you implementing it.

**Comment by jsmartt** [comment]
@tmiotto , correct. We'd definitely have to set a limit

**Comment by ricardogpsf** [comment]
@jsmartt I'm okay too with the idea of implementation.
