### ISSUE TITLE
[API300] Why is Switch the only resource that directly implements #set_scope_uris?

### ISSUE THREAD

**Issue by tmiotto** [HewlettPackard/oneview-sdk-ruby#146]
### Scenario/Intent
I'm trying to understand why API300 Switch has the `#set_scope_uris`, but other resources don't, like, server_hardware, enclosure...

I know it is the only patch operation it supports **right now** but, if we are trying to have some consistency, or every single patch operation has to be implemented as a separate method, or the API300 Switch should implement a `#patch` method.

### Environment Details
 - **OneView SDK Version:** 3.1.0
 - **OneView Client API Version:** 300

**Comment by ricardogpsf** [comment]
With the #133 some helper methods (add_scope, remove_scope, replace_scopes) were added to Enclosure and ServerHardware too.
And with #147 the helper methods were added to LogicalSwitch too.
