### ISSUE TITLE
[I3S] Integration tests are not supporting multiple tags for test selection

### ISSUE THREAD

**Issue by tmiotto** [HewlettPackard/oneview-sdk-ruby#150]
### Scenario/Intent
To run the SDK tests currently, it is needed to specify one of the tags along with rspec `--tag ~unit`. The current architechiture is not supporting using multiple tags to specify an specific test with a specific API.

In the future this may cause the SDK to have *<api_number>  x  <test_strategy>* tags, insted having the sum of them.

### Environment Details
 - **OneView SDK Version:** 3.1.0

### Steps to Reproduce
Run the i3s integration tests.

### Expected Result
I want to be able to run them specifying `rspec <folder> --tag integration --tag i3s`.

### Actual Result
I am able to run them specifying `rspec <folder> --tag integration_i3s`.

**Comment by AsisBagga** [comment]
This SDK has limited support and will not be actively developed for the foreseeable future.
