### ISSUE TITLE
OneviewSDK.resource_named doesn't work for FirmwareBundle

### ISSUE THREAD

**Issue by jsmartt** [HewlettPackard/oneview-sdk-ruby#176]
### Scenario/Intent
Retrieve the FirmwareBundle resource using the `OneviewSDK.resource_named` method.

### Environment Details
 - **OneView SDK Version:** 4.0.0

### Steps to Reproduce
```ruby
OneviewSDK.resource_named(:FirmwareBundle)  # returns nil
```

### Expected Result
Return the FirmwareBundle class

### Actual Result
Returns nil.

This is because in the [resource_named method](https://github.com/HewlettPackard/oneview-sdk-ruby/blob/master/lib/oneview-sdk/resource/api200.rb#L24), we only return classes that are children of `OneviewSDK::Resource`. This class (and possibly others) are not children, but are valid resources

**Comment by tmiotto** [comment]
I actually have my doubts if it should be a resource or a method inside `OneviewSDK::FirmwareDriver` since its only function is to upload  a Firmware Driver to the appliance.
