### ISSUE TITLE
Concurrent execution of long-running tasks

### ISSUE THREAD

**Issue by jsmartt** [HewlettPackard/oneview-sdk-ruby#180]
### Scenario/Intent
I would like to do multiple long-running tasks concurrently using the helper methods, but the helper methods each wait for the task to complete before returning. The response_handler method already supports a `wait_on_task` property, and it would be nice to expose that option through the helper methods as well.

The [enclosure resource](https://github.com/HewlettPackard/oneview-sdk-ruby/blob/master/lib/oneview-sdk/resource/api200/enclosure.rb) is a good example of a resource that would benefit from such functionality, but it also provides a good example of the issues we may run into. For example, if we added a `wait_on_task` parameter to those methods, we would have to return a task uri instead of the normal return value (or set it as an attribute), and we also may not be able to do some steps that come after the main task (for instance, after adding the enclosure, we rename it; after re-applying the configuration, we set the data). What would be the best way to handle these sorts of issues? Make a new method with documented differences in functionality and return values, or add the parameter to existing methods and just do the best we can to document the behavior? I'd rather create a new method, but that means adding a lot more methods and possibly making things a little confusing because now 2 methods to do similar things (but with some small but important differences).

I'd like to hear others thoughts on this topic

### Environment Details
 - **OneView SDK Version:** 4.0.0
 - **OneView Appliance Version:** All

**Comment by aalexmonteiro** [comment]
I prefer to change existing methods because it will be easier to maintain. The idea of using a parameter seems good to me.

**Comment by jsmartt** [comment]
I guess a third option would be to keep the method names as-is, add the wait_on_task property, and if it is false, set a new resource attribute (task_uri), and return the correct type. So the return values would be consistent, and you could still wait for the task later. Additionally, we could have a method on the resource class to wait for all task(s). The task data would travel with the object, so the user wouldn't have to worry about keeping track of the task uris. The only downside to this is that for resources where additional things are done in those methods after the task is done (ie, rename enclosure after adding), the user would have to do those things manually (this will be the case for any option though).

**Comment by ricardogpsf** [comment]
I liked idea of to change existing methods for receive the new parameter 'wait_for_task' (with default value true). But I think that one good way too is return a Task Object (we will create a class Task) that can receive a callback with additional actions after task be done. And the Task object will have `wait ` method for wait the task conclusion.
What do you think, @jsmartt @tmiotto @fgbulsoni @aalexmonteiro

**Comment by jsmartt** [comment]
I think that returning tasks (different return values) would be too disruptive at this point. People's code relies on those return values, and if we changed them up or made them inconsistent, I think we'd cause some issues. I'm certainly not opposed to having a Task resource, but I'm not sure it solves this issue just yet.

If we return a task resource then we also have to deal with those 2 separate objects that are related to that one resource. It seems natural to me to have the tasks associated with the resource stored inside that object. One object to deal with. Just my thoughts

**Comment by aalexmonteiro** [comment]
> Additionally, we could have a method on the resource class to wait for all task(s).

I like this as well as the use of callback proposed by @ricardogpsf and that could be used the idiomatic approach to do additional things.

**Comment by jsmartt** [comment]
The idea of callbacks is very interesting. I'm having trouble understanding how it would be used though. @ricardogpsf , do you have some sort of example you can provide pseudo-code for?

**Comment by ricardogpsf** [comment]
@jsmartt , I thinking something like this:
```ruby
class Task
  def initialize(data, &block)
    @data = data
    @action = block
  end
  
  def wait
    # wait the task conclusion 
    # result = wait_for_task code
    @action.call(result)
    result
  end
end

def create(wait_for_task = true)
  # response_data = rest_get('uri', wait_for_task)
  if wait_for_task
    response_data
  else
    Task.new(response_data) do |result_task|
      # action after task be done
      result_task['name'] = 'Changing something'
    end
  end
end

task = create(false)
task.wait
```

**Comment by aalexmonteiro** [comment]
Another way this could be, but this proposal of the @ricardogpsf looks good for me.

```ruby
#method on my_class
def create(wait_on_task = true)
  # response_data = rest_get('uri', wait_for_task)
  if wait_on_task
    response_data
  else
    yield OneviewSDK::resource.wait_for_task
  end
end


# method on resource class
def wait_for_task
  # waiting the task
  return # result_task
end


# using the method create

my_class = new_instance

my_class.create(false) do |result_task|
    # make something
end

# or when is not necessary wait task

my_class.create
```

**Comment by jsmartt** [comment]
What about threads? I guess we could use those to accomplish something similar, and that way we wouldn't need callbacks, but would still be able to do all the same tasks in order (using the same code too). Like this:

```ruby
class Resource
  ...
  def create(wait_on_task = true)
    response = @client.rest_post(@uri, @data)
    @client.response_handler(response, false) # Make sure it didn't return an error, but don't wait on the task
    t = Thread.new do
      # Do all the normal creation & waiting tasks
      new_data = @client.response_handler(response)
      set_all(new_data)
      # Do other things here if necessary
    end
    t.join if wait_on_task
    return self # Or whatever the return value is normally. This must stay the same.
  end

  def wait_for_tasks
    @threads.each { |t| t.join }
  end
  ...
end

item = OneviewSDK::Resource.new(client, options)
item2 = OneviewSDK::Resource.new(client, options)

# Start the creation tasks and return immediately
item.create(false)
item2.create(false)

# Do other things

# Then when I need to wait (because of a resource dependency) or I'm at the end of my configuration script...
item.wait_for_tasks
item2.wait_for_tasks
```

**Comment by ricardogpsf** [comment]
Yes. It's nice.
I imagined that the final user will create a thread encapsulating the Task class.
But, seeing your code, I think so the Task class could be a wrap for work with Threads, and the final user to know how to work with the tasks (if he want wait for them or no)
But your code is nice to me, @jsmartt . The resource class can know how work withyour own tasks/threads. =)

**Comment by jsmartt** [comment]
Update: I did a bit of work implementing some of the basics on [this branch](https://github.com/HewlettPackard/oneview-sdk-ruby/compare/master...threads), but at this point it seems like it might be better to just leave it up to the client to handle the threading. They could just as easily do this:

```ruby
item = OneviewSDK::Resource.new(client, options)
item2 = OneviewSDK::Resource.new(client, options2)

t = Thread.new do
  item.create
  item2.create
end

# Do other things

# Then when I need to wait (because of a resource dependency) or I'm at the end of my configuration script...
t.join
```
