### ISSUE TITLE
Coveralls badge showing coverage as unknown

### ISSUE THREAD

**Issue by fgbulsoni** [HewlettPackard/oneview-sdk-ruby#184]
### Scenario/Intent
See the % of code coverage through the coveralls badge in the readme.

Apparently, according to coveralls documentation, what is missing is:
1. add `gem 'coveralls', require: false` to the gemfile
2. add `require coveralls` to the top of the spec_helper.rb file and add the following after the requires:
```ruby
Coveralls.wear!

SimpleCov.formatters = [
  SimpleCov::Formatter::HTMLFormatter,
  Coveralls::SimpleCov::Formatter
]
```

### Steps to Reproduce
Visit the [project github](https://github.com/HewlettPackard/oneview-sdk-ruby). Or look here:  [![Coverage Status](https://coveralls.io/repos/github/HewlettPackard/oneview-sdk-ruby/badge.svg?branch=master)](https://coveralls.io/github/HewlettPackard/oneview-sdk-ruby?branch=master)

### Expected Result
The badge is up to date with the % of code covered

### Actual Result
 [![Coverage Status](https://coveralls.io/repos/github/HewlettPackard/oneview-sdk-ruby/badge.svg?branch=master)](https://coveralls.io/github/HewlettPackard/oneview-sdk-ruby?branch=master)

**Comment by jsmartt** [comment]
Ah. Thanks. I thought maybe it would take care of it automatically once it was merged & had a chance to run.
