### ISSUE TITLE
Improvements on the creation of the clients for integration tests

### ISSUE THREAD

**Issue by aalexmonteiro** [HewlettPackard/oneview-sdk-ruby#209]
### Scenario/Intent
Currently, I can only perform integration tests if both the C7000 and synergy configuration files are configured. Because in the creation of shared_context, the clients of both are created together, creating a dependency between the two files. It would be nice to remove this dependency and if you just want to run tests for synergy, configure only the synergy configuration file.

Another example would be some server is not available. The server running the C7000 appliance is available, but the Synergy server is not available. In this case, it is necessary to change the credentials and IP in the Synergy configuration file, otherwise a timeout error occurs, and I only want to run the tests for C7000.

### Environment Details
 - **OneView SDK Version: current master repo
 - **OneView Appliance Version: any
 - **OneView Client API Version: any
 - **Ruby Version: 2.2.3+
 - **Platform: Any

### Expected Result
Independent configuration for execution of the integration tests.

### Actual Result
Configuration dependency exists between C7000 and Synergy.

**Comment by AsisBagga** [comment]
This SDK has limited support and will not be actively developed for the foreseeable future.
