### ISSUE TITLE
Artifact bundle method `get_backups` naming and return

### ISSUE THREAD

**Issue by fgbulsoni** [HewlettPackard/oneview-sdk-ruby#211]
### Scenario/Intent
The i3s appliance only allows one backup at a time on the whole appliance. Thus, we'd never be able to get multiple backups and it is plain weird that the name of the method is _get_backup**s**_ in that case. 
Also, with that being the case, the method should not return an array containing a single object, it should return the object.

### Expected Result
Expected a `get_backup` method which returns the appliance's backup

### Actual Result
`get_backups` method which returns an array containing the single backup from the appliance

**Comment by ricardogpsf** [comment]
I can be wrong, but the reason why the appliance returns just one backup is because just one deployment group there is in appliance.
The backups are associated to some deployment group, so if there are more than one deployment group, then we will have more than one backup.

**Comment by fgbulsoni** [comment]
Snippet from the i3s documentation which led to this issue:
`Creates a backup bundle with all the artifacts present on the appliance. At any given point only one backup bundle will exist on the appliance. Specify all the attributes without default values in the POST body.`
If `appliance` in this context means specific deployment groups and we can actually have more of those, and thus more backups, how can I get a specific backup? I feel we're missing this capacity at the moment.

**Comment by AsisBagga** [comment]
This SDK has limited support and will not be actively developed for the foreseeable future.
