### ISSUE TITLE
Unable to create a Server Profile with Deployment Plan settings

### ISSUE THREAD

**Issue by marikrg** [HewlettPackard/oneview-sdk-ruby#212]
### Scenario/Intent
I'm not able to create any Server Profile using an existing Deployment Plan.
There is no way to get the URI of a Deployment Plan, unless copying it from the GUI.

The GET /rest/os-deployment-plans/{id}, from the OneView API 300, returns two URIs in the response data:

```json
"nativePlanUri": "/rest/oedeploymentplan/c85a5181-8c4c-421c-a018-5b5e69082bce"
```
and

```json
"uri": "/rest/os-deployment-plans/18d42e6d-f64e-422b-affd-7185603ab9c4"
```

The `nativePlanUri` is the same URI from ImageStreamer, and it doesn't work for Server Profile creation.
I must pass in the `uri`, which is the canonical URI.

Follow an example of the Deployment Setting from an existing Server Profile:
```json
    "osDeploymentSettings": {
        "osDeploymentPlanUri": "/rest/os-deployment-plans/18d42e6d-f64e-422b-affd-7185603ab9c4",
        "osVolumeUri": "/rest/deployed-targets/c9bc7b3c-e916-425f-9dad-6c304e1140e1",
        "osCustomAttributes": [
            {
                "name": "hostname",
                "value": "newhostname"
            }
        ]
    }
```

Thus, the endpoints from the OneView Rest API 300 are really useful and must be implemented as soon as possible.

### Environment Details
 - **OneView SDK Version:** any
 - **OneView Appliance Version:** 3.0 / Synergy
 - **OneView Client API Version:** 300
 - **Ruby Version:** any
 - **Platform:** Linux/Windows

### Steps to Reproduce
Call `OneviewSDK::API300::Synergy::OSDeploymentPlan.find_by` (or anything similar, not sure about the class name)

### Expected Result
Return a list of OS Deployment Plans.

### Actual Result
This resource is not implemented yet.

**Comment by tmiotto** [comment]
Well, it's still missing the `ServerProfile#set_os_deployment_plan`.
