### ISSUE TITLE
Make resource for MSMB

### ISSUE THREAD

**Issue by jsmartt** [HewlettPackard/oneview-sdk-ruby#229]
### Scenario/Intent
We have a resource to connect to the SCMB, but it would be nice to have one for the MSMB too. At this point, I think the only change **might** be to just bind to the `'msmb'` exchange. See [here](https://github.com/HewlettPackard/oneview-sdk-ruby/blob/master/lib/oneview-sdk/scmb.rb#L68)

### Environment Details
 - **OneView SDK Version:** 4.3.0

**Comment by AsisBagga** [comment]
This SDK has limited support and will not be actively developed for the foreseeable future.
