### ISSUE TITLE
OneviewSDK::Rest can't properly handle IPv6 addresses

### ISSUE THREAD

**Issue by vranystepan** [HewlettPackard/oneview-sdk-ruby#244]
### Scenario/Intent
This is natural behavior for URI library. See following example:
```ruby
URI("https://[FE80::C800:EFF:FE74:8]").host # => "[FE80::C800:EFF:FE74:8]"
URI("https://[FE80::C800:EFF:FE74:8]").hostname # => "FE80::C800:EFF:FE74:8"
```
First example does not return valid IPv6 address so it OneviewSDK::Rest can't work properly.
https://github.com/HewlettPackard/oneview-sdk-ruby/blob/master/lib/oneview-sdk/rest.rb#L240

### Environment Details
 - **Ruby Version:** 2.4.1 (but generally does not matter)
 - **Platform:** Linux, Windows

### Steps to Reproduce
See `Scenario/Intent
`
### Fix?
Replace` .host` with `.hostname` (at the moment I can see only one occurrence): 
https://github.com/HewlettPackard/oneview-sdk-ruby/blob/master/lib/oneview-sdk/rest.rb#L240

### Potential impact
None. FQDNs and IPv4 URIs should be handled same way:
```ruby
URI("https://oneview.local").hostname # => "oneview.local"
URI("https://oneview.local").host # => "oneview.local"
URI("https://1.2.3.4").hostname # => "1.2.3.4"
URI("https://1.2.3.4").host # => "1.2.3.4"
```

**Comment by jsmartt** [comment]
👍
