### ISSUE TITLE
Improve error messages - Read Timeout and 503 error

### ISSUE THREAD

**Issue by aalexmonteiro** [HewlettPackard/oneview-sdk-ruby#248]
### Scenario/Intent
When a read-out timeout or error 503 occurs, the error messages are not very clear. The SDK should return a message with more information about the error to the user.

### Environment Details
 - **OneView SDK Version: current master repo
 - **OneView Appliance Version: Any
 - **OneView Client API Version: Any
 - **Ruby Version: 2.2.3+
 - **Platform: Any

### Steps to Reproduce
Attempt a connection with offline oneview to return a timeout.

### Expected Result
A error message with more information about the error.

### Actual Result
A error message without details about the error.

**Comment by AsisBagga** [comment]
This SDK has limited support and will not be actively developed for the foreseeable future.
