### ISSUE TITLE
Add ID Pools IPv4 Subnets / Ranges resource

### ISSUE THREAD

**Issue by vranystepan** [HewlettPackard/oneview-sdk-ruby#262]
### Scenario/Intent
As mentioned in HewlettPackard/oneview-chef#294, there's lacking support for IPv4 ID Pools: `Subnets` and `Ranges`. 

### Documentation
- http://h17007.www1.hpe.com/docs/enterprise/servers/oneview3.0/cic-api/en/api-docs/current/index.html#rest/id-pools/ipv4/subnets
- http://h17007.www1.hpe.com/docs/enterprise/servers/oneview3.0/cic-api/en/api-docs/current/index.html#rest/id-pools/ipv4/ranges

### New oneview-sdk resources (proposals)
Both resources are relevant for API300 Synergy only (I will confirm soon).
- api300/Synergy `IDPoolSubnet`
- api300/Synergy `IDPoolRange`

**Comment by AsisBagga** [comment]
This SDK has limited support and will not be actively developed for the foreseeable future.
