### ISSUE TITLE
Improvement in methods 'retrieve!' and 'exists?' - Volume API500

### ISSUE THREAD

**Issue by aalexmonteiro** [HewlettPackard/oneview-sdk-ruby#282]
### Scenario/Intent
Currently, the ```retrieve!``` and ```exists?``` methods can search a volume API500 by the ```name``` attribute on ```data``` or within ```properties```. In the SDK is verified the existence of ```properties```, if in case does not exist the parent method is called and the search will be by ```name``` within ```data```. I think there is an improvement that can be made. Maybe it would be good to search first by ```name``` within ```data```. Currently the method ```retrieve!``` throw an exception (IncompleteResource), if the attribute ```name``` or ```uri``` has not been passed, I can capture this exception and then go search for ```name``` within ```properties```.

@tmiotto , @fgbulsoni , @ricardogpsf .What do you think?

**Comment by ricardogpsf** [comment]
It is more simples if you set the name as the root attribute on the initialize method, when user are creating a new instance of resource.
Something like:
´´´ruby
def initialize(client, params = {}, api_ver = nil)
  super
  # Default values:
  @data['type'] ||= 'StorageVolumeAttachment'
  @data['name'] ||= @data['properties']['name'] if @data['properties'].@data['properties'](Hash)
end
´´´

**Comment by aalexmonteiro** [comment]
No change needed. Closing this question.
