### ISSUE TITLE
Remove the deprecated methods to next release

### ISSUE THREAD

**Issue by ricardogpsf** [HewlettPackard/oneview-sdk-ruby#289]
### Scenario/Intent
Some methods of current release 5 are marked as deprecated, we should remove them to next release.

### Deprecated Methods
- [ ] `#set_scope_uris` at [... /api300/c7000/switch.rb](https://github.com/HewlettPackard/oneview-sdk-ruby/blob/master/lib/oneview-sdk/resource/api300/c7000/switch.rb#L22-L27)
- [ ] `::add` at [... /api500/c7000/volume.rb](https://github.com/HewlettPackard/oneview-sdk-ruby/blob/master/lib/oneview-sdk/resource/api500/c7000/volume.rb#L126-L143)

**Comment by AsisBagga** [comment]
This SDK has limited support and will not be actively developed for the foreseeable future.
