### ISSUE TITLE
Overridden methods without receiving header parameter

### ISSUE THREAD

**Issue by tmiotto** [HewlettPackard/oneview-sdk-ruby#294]
### Scenario/Intent
I'm trying to delete a API300::C7000::Scope passing a header as a parameter, but I can't and the default code fails (Resource#create!).

### Environment Details
 - **OneView SDK Version:** 5.2.0
 - **OneView Client API Version:** API300

### Steps to Reproduce
Run  API300::C7000::Scope#create!

### Expected Result
The scope should be deleted and created successfully

### Actual Result
It fails saying the delete won't receive any arguments (the header)

### Root cause
API300::C7000::Scope is overriding the delete without parameters, so it is causing it to fail.

**Comment by ricardogpsf** [comment]
The default code `create!` do 3 calls, it calls the `retrieve!`, `delete` and `create` methods. So, any resource that overwrite that methods without the argument "header", the default implementation of create! will fail. Below we can see all resources that have overwrote at least one of the `retrieve!`, `delete` or `create` methods and which will fail when call the `create!` method.

We can mark the checkbox if some one that resources is ok after some change.

 - [ ] storage_system
   - [ ] `#retrieve!`method
 - [ ] storage_pool
   - [ ] `#retrieve!`method
 - [ ] server_hardware
   - [ ] `#retrieve!`method
 - [ ] user
   - [ ] `#create`method
 - [ ] logical_switch
   - [ ] `#create`method
 - [ ] logical_interconnect_group
   - [ ] `#create`method
 - [ ] logical_interconnect
   - [ ] `#create`method
   - [ ] `#delete`method
   maybe in this case, the good way is overwriting the `#create!` method
 - [ ] volume
   - [ ] `#retrieve!`method
   - [ ] `#create`method
   - [ ] `#delete`method
 - [ ] volume_template
   - [ ] `#delete`method
 - [ ] scope
   - [ ] `#delete`method
