### ISSUE TITLE
Bulk creation of ethernet networks does not work on puppet

### ISSUE THREAD

**Issue by madhav-bharadwaj** [HewlettPackard/oneview-sdk-ruby#357]
### Scenario/Intent
Trying to execute /rest/ethernet-networks/bulk in puppet but it fails.
The request body does not have name attribute but the exists? method in ruby searches for the resource existence using name. So this endpoint fails and throws and exception.

### Environment Details
 - **OneView SDK Version:** 5.5.0
 - **OneView Appliance Version:** 4.0
 - **OneView Client API Version:** 500
 - **Ruby Version:** 2.4
 - **Platform:** Ubuntu 16,04

### Steps to Reproduce
Run ethernet networks manifest

### Expected Result
Create bulk ethernet networks

### Actual Result
Exception thrown.
"Must set resource URI or name before trying to retrieve!

**Comment by AsisBagga** [comment]
This SDK has limited support and will not be actively developed for the foreseeable future.
