### ISSUE TITLE
Integration tests for scope resource are failing

### ISSUE THREAD

**Issue by soodpr** [HewlettPackard/oneview-sdk-ruby#358]
### Scenario/Intent
Integration tests for scope resource are failing

### Environment Details
 - **OneView SDK Version:** [5.5.0]
 - **OneView Appliance Version:** [4.0]
 - **OneView Client API Version:** [600]
 - **Ruby Version:** [2.4.1]
 - **Platform:** [Ubuntu 16.04]

### Steps to Reproduce
run rspec spec/integration/resource/api600/c7000/scope/update_spec.rb or rspec spec/integration/resource/api600/c7000/scope/create_spec.rb

### Expected Result
Tests should run without any fail

### Actual Result
Few tests were failing

**Comment by AsisBagga** [comment]
This SDK has limited support and will not be actively developed for the foreseeable future.
