### ISSUE TITLE
Update Gem-Pry version 

### ISSUE THREAD

**Issue by chebroluharika** [HewlettPackard/oneview-sdk-ruby#395]
**Scenario/Intent**
Update Gem-Pry version in such a way that Travis build should success for every build.

**Environment Details**
 - **Ruby Version:** 2.5.1
 - **Platform:** radhat

**Expected Result**
Travis build must be in success state after every build.
No methods should get deprecated.

**Comment by AsisBagga** [comment]
This SDK has limited support and will not be actively developed for the foreseeable future.
