### ISSUE TITLE
Failing to install oneview-sdk gem as runtime environment

### ISSUE THREAD

**Issue by riconem** [HewlettPackard/oneview-sdk-ruby#473]
### Scenario/Intent
Install oneview-sdk gem as runtime environment.

### Environment Details
 - **OneView SDK Version:** 5.16.0
 - **OneView Client API Version:** 1200
 - **Ruby Version:** 2.4.4

### Steps to Reproduce
Install oneview-sdk gem as runtime environment.

### Expected Result
oneview-sdk gem as runtime environment.

### Actual Result
when I execute `oneview-sdk-ruby --help` I will get this error:
```
/opt/puppetlabs/puppet/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:120:in `require': cannot load such file -- addressable (LoadError)
        from /opt/puppetlabs/puppet/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:120:in `require'
```

### TODO
Please add the gem `addressable` to `spec.add_runtime_dependency` in [oneview-sdk.gemspec](https://github.com/HewlettPackard/oneview-sdk-ruby/blob/master/oneview-sdk.gemspec)

**Comment by VenkateshRavula** [comment]
@riconem , Thanks for pointing this. We are looking into it.

**Comment by AsisBagga** [comment]
@riconem Hi Enrico, Thank you. This changes will reflects is upcoming releases. 
Before we close the issue let me know if you have any other concerns for the same.

**Comment by riconem** [comment]
@AsisBagga Thank you. Everything is fine. 👍
