### ISSUE TITLE
Integration tests use hardcoded URIs

### ISSUE THREAD

**Issue by jsmartt** [HewlettPackard/oneview-sdk-ruby#82]
Hardcoded URIs should be replaced with GET calls to fetch existing resources by name. Otherwise nobody but the person who created the test can run the integration tests (or someone on the same OV instance)

Problem Files:
- [x] [enclosure/create_spec.rb](./../blob/master/spec/integration/resource/enclosure/create_spec.rb)
- [ ] [logical_interconnect_qos.json](./../blob/master/spec/support/fixtures/integration/logical_interconnect_qos.json)
- [ ] [storage_pool.json](./../blob/master/spec/support/fixtures/integration/storage_pool.json)
- [ ] [volume_template.json](./../blob/master/spec/support/fixtures/integration/volume_template.json)
- [ ] Others?

**Comment by AsisBagga** [comment]
This SDK has limited support and will not be actively developed for the foreseeable future.
