### ISSUE TITLE
Add error handling to SAN Manager #self.get_default_connection_info

### ISSUE THREAD

**Issue by tmiotto** [HewlettPackard/oneview-sdk-ruby#84]
We need to figure out how to report if it could not find any default connection info using the provider_name attribute. The current error reporting is not clear, so we need to improve it.

I see two alternatives:
1. Raise exception if no `desired_provider` is found
2. Return `nil` if no `desired_provider` is found

**Comment by AsisBagga** [comment]
This SDK has limited support and will not be actively developed for the foreseeable future."
